### ISSUE TITLE
Comments: falsehoodInWarTime

### ISSUE THREAD

**Issue by MyLittleCrab** [JustAddAcid/JustAddAcid.github.io#23]
https://nosoff.info/posts/falsehoodInWarTime

**Comment by MyLittleCrab** [comment]
Комменты с правками желательно создавать в формате:

> старый текст

заменить на 
> новый текст

Ну и больше ориентироваться на оригинальную книгу. Между красивостью и соответствию оригиналу лучше выбирать соответствие. 👍

**Comment by gtrus21** [comment]
А есть версия в виде уже готовой книги? EPUB или FB2
